services:
  - type: web
    name: hyper-trading-system
    env: python
    buildCommand: pip install -r deployment/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ALPHA_VANTAGE_API_KEY
        value: RXV371OVWXK6BQ17
      - key: PORT
        value: 8000
      - key: DEBUG
        value: false
    healthCheckPath: /health
    plan: starter
