services:
  - type: web
    name: hyper-trading-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ALPHA_VANTAGE_API_KEY
        value: OKUH0GNJE410ONTC
      - key: DEBUG
        value: true
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /health
    plan: starter
