
services:
  - type: web
    name: hypertrends-v4
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --worker-class uvicorn.workers.UvicornWorker --workers 1 --timeout 120
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEMO_MODE
        value: "false"
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHON_VERSION
        value: "3.11"
      - key: RH_USERNAME
        value: "your@email.com"  # 🔒 Replace with your Robinhood email
      - key: RH_PASSWORD
        value: "yourSecurePassword"  # 🔒 Replace with your Robinhood password

      # Optional future API integrations
      - key: NEWS_API_KEY
        value: ""
      - key: REDDIT_CLIENT_ID
        value: ""
      - key: REDDIT_SECRET
        value: ""
      - key: TWITTER_BEARER_TOKEN
        value: ""

      # Performance tuning (optional)
      - key: WORKERS
        value: "1"
      - key: MAX_CONNECTIONS
        value: "100"
      - key: KEEPALIVE_TIMEOUT
        value: "65"

    disk:
      name: hyper-data
      mountPath: /app/data
      sizeGB: 1
