services:
  - type: web
    name: hypertrading-v4
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --worker-class uvicorn.workers.UvicornWorker --workers 1 --timeout 120
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEMO_MODE
        value: "true"
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHON_VERSION
        value: "3.11"
      - key: RH_USERNAME
        value: "your@email.com"
      - key: RH_PASSWORD
        value: "yourSecurePassword"
    disk:
      name: hyper-data
      mountPath: /app/data
      sizeGB: 1