services:

- type: web
  name: hypertrends-v4
  env: python
  plan: starter
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --worker-class uvicorn.workers.UvicornWorker --workers 1 --timeout 120 --keep-alive 65
  healthCheckPath: /health
  autoDeploy: true
  envVars:

  # Core Configuration
  - key: ENVIRONMENT
    value: "production"
  - key: DEMO_MODE
    value: "true"
  - key: LOG_LEVEL
    value: "INFO"
  - key: PYTHON_VERSION
    value: "3.11"

  # Port Configuration (Critical for Render)
  - key: PORT
    value: "10000"
  - key: HOST
    value: "0.0.0.0"

  # ==== Alpaca API Keys and TRADING MODE ====
  # --------- PAPER (default) ---------
  - key: TRADING_MODE
    value: "paper"
  - key: APCA_API_KEY_ID
    value: "PK2AML2QK9VUI5J1G1BC"
  - key: APCA_API_SECRET_KEY
    value: "3IDsz3oeGliJeBG9h35V8OAAcjDH6hqMLoJDXpif"

  # --------- LIVE (comment out paper above, uncomment below to use live trading) ---------
  # - key: TRADING_MODE
  #   value: "live"
  # - key: APCA_API_KEY_ID
  #   value: "<YOUR_LIVE_KEY_ID>"
  # - key: APCA_API_SECRET_KEY
  #   value: "<YOUR_LIVE_SECRET_KEY>"

  # Performance Settings
  - key: WORKERS
    value: "1"
  - key: MAX_CONNECTIONS
    value: "100"
  - key: KEEPALIVE_TIMEOUT
    value: "65"

  # Security Settings
  - key: CORS_ORIGINS
    value: "*"

  # Optional API Keys for Future Features
  - key: NEWS_API_KEY
    value: ""
  - key: REDDIT_CLIENT_ID
    value: ""
  - key: REDDIT_SECRET
    value: ""
  - key: TWITTER_BEARER_TOKEN
    value: ""

  disk:
    name: hyper-data
    mountPath: /app/data
    sizeGB: 1
